name: Issues - Manual Workflow Approval
description: Pause a workflow and get user approval to continue
inputs:
  approvers:
    description: Required approvers
    required: true
  secret:
    description: Secret
    required: true
  minimum-approvals:
    description: Minimum number of approvals to progress workflow
    required: false
  approval-wait:
    description: Timeout before approval
    required: true
  issue-title:
    description: Github issue title
    required: false
  issue-body:
    description: Github issue body
    required: false
runs:
  using: docker
  image: 'docker://ghcr.io/macnev2013/manual-approval:v1.0.17'
