name: Lint & Testing

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Linting & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make build
        env:
          VERSION: latest
      - name: Test
        run: make test
